In [13]:
#PASO 1: Cargar Packages y data set
import pandas as pd #Análisis de datos
import matplotlib.pyplot as plt #Gráficsa de calidad de publicación
import statsmodels.api as sm #Funciones de series temporales
import numpy as np #Funciones matemáticas: algoritmos, matrices, álgebra
from statsmodels.tsa.arima_model import ARIMA
%matplotlib inline
pd.set_option('precision',2)
datos = pd.read_csv("D:/DataScience/AirPassengers.csv", parse_dates=["Month"], index_col="Month")
datos.head(15)

            #Passengers
Month
1949-01-01          112
1949-02-01          118
1949-03-01          132
1949-04-01          129
1949-05-01          121
1949-06-01          135
1949-07-01          148
1949-08-01          148
1949-09-01          136
1949-10-01          119
1949-11-01          104
1949-12-01          118
1950-01-01          115
1950-02-01          126
1950-03-01          141

In [14]:
#Paso 2: Selección de los datos donde se realizará el análisis
datos['1949':'1960']['#Passengers']

Month
1949-01-01    112
1949-02-01    118
1949-03-01    132
1949-04-01    129
1949-05-01    121
1949-06-01    135
1949-07-01    148
1949-08-01    148
1949-09-01    136
1949-10-01    119
1949-11-01    104
1949-12-01    118
1950-01-01    115
1950-02-01    126
1950-03-01    141
1950-04-01    135
1950-05-01    125
1950-06-01    149
1950-07-01    170
1950-08-01    170
1950-09-01    158
1950-10-01    133
1950-11-01    114
1950-12-01    140
1951-01-01    145
1951-02-01    150
1951-03-01    178
1951-04-01    163
1951-05-01    172
1951-06-01    178
             ...
1958-07-01    491
1958-08-01    505
1958-09-01    404
1958-10-01    359
1958-11-01    310
1958-12-01    337
1959-01-01    360
1959-02-01    342
1959-03-01    406
1959-04-01    396
1959-05-01    420
1959-06-01    472
1959-07-01    548
1959-08-01    559
1959-09-01    463
1959-10-01    407
1959-11-01    362
1959-12-01    405
1960-01-01    417
1960-02-01    391
1960-03-01    419
1960-04-01    461
1960-05-01    472
1960-06-01    535
1960-07-01    622
1960-08-01    606
1960-09-01    508
1960-10-01    461
1960-11-01    390
1960-12-01    432
Name: #Passengers, Length: 144, dtype: int64

In [28]:
#PASO 3: Determinación del tipo de modelo (Estacionario o no Estacionario)
from statsmodels.tsa.stattools import adfuller
def test_stationarity(timeseries):

#Estadísticas de la determinación del balanceo (Media móvil y Desviación Estándar)
    rolmean = pd.rolling_mean(timeseries, window=12)
    rolstd = pd.rolling_std(timeseries, window=12)
#Graficar las estadísticas del balanceo
    orig = plt.plt(timeseries, color='blue', label='Original')
    mean = plt.plot(rolmean, color='red', label='Media Movil')
    std = plt.plot(rolstd, color='black', label = 'Desviacion Estandar')
    plt.legend(loc='best')
    plt.title('Media Movil y Desviación Estandar')
    plt.show(block=False)
    test_stationarity(datos['#Passengers'])

In [29]:
#PASO 4: Calculo de media móvil
moving_avg = pd.rolling_mean(datos['#Passengers'], 12)
datos['#Passengers'].plot()
#Gráfica de la media móvil
moving_avg.plot(label='Media Movil', color='red')
plt.title('Media Móvil')
plt.legend(loc='best')

AttributeError: module 'pandas' has no attribute 'rolling_mean'